// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from @react-native-community/slider
using SliderWindows;

// Namespaces from @react-native-picker/picker
using ReactNativePicker;

// Namespaces from react-native-screens
using RNScreens;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from @react-native-community/slider
            packageProviders.Add(new SliderWindows.ReactPackageProvider());
            // IReactPackageProviders from @react-native-picker/picker
            packageProviders.Add(new ReactNativePicker.ReactPackageProvider());
            // IReactPackageProviders from react-native-screens
            packageProviders.Add(new RNScreens.ReactPackageProvider());
        }
    }
}
